FROM stephengpope/no-code-architects-toolkit@sha256:2bed440598f237ad636e12b22ada894b75e3bbd411aef97a158315de4a2e2a2b

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends fontconfig fonts-noto-cjk && \
    rm -rf /var/lib/apt/lists/* && fc-cache -f -v

ENV LANG=ja_JP.UTF-8 LANGUAGE=ja_JP:ja LC_ALL=ja_JP.UTF-8
